@extends('layouts.tabler.lecturer', ['title' => 'Presensi Kelas', 'heading' => 'Presensi kelas'])

@section('content')
@if(session('success'))<x-tabler.alert type="success">{{ session('success') }}</x-tabler.alert>@endif
@if($errors->any())<x-tabler.alert type="danger">{{ $errors->first() }}</x-tabler.alert>@endif
@if(session('attendance_credential'))<x-tabler.alert type="info"><strong>Kredensial sesi {{ session('attendance_session_id') }}:</strong> <code class="user-select-all">{{ session('attendance_credential') }}</code><div class="small mt-1">Bagikan hanya kepada peserta kelas. Kredensial ini hanya ditampilkan sekali.</div></x-tabler.alert>@endif
<div class="row row-cards">
@forelse($sections as $section)
    <div class="col-12"><x-tabler.card title="{{ $section->offering?->course?->name }} · {{ $section->code }}"><div class="row row-cards">
    @forelse($section->meetings as $meeting)
        @php($session = $meeting->attendanceSessions->sortByDesc('created_at')->first())
        <div class="col-12 col-lg-6"><div class="card card-sm h-100"><div class="card-body"><div class="d-flex align-items-start"><span class="avatar bg-primary-lt text-primary me-3">{{ $meeting->meeting_number }}</span><div class="flex-fill"><div class="fw-semibold">{{ $meeting->topic ?: 'Pertemuan '.$meeting->meeting_number }}</div><div class="text-secondary small">{{ $meeting->meeting_date->translatedFormat('d M Y') }}</div></div>@if($session)<x-tabler.status :value="$session->status" />@endif</div>
        @if(!$session || $session->status !== 'open' || $session->expires_at?->isPast())<button class="btn btn-outline-primary w-100 mt-3" data-bs-toggle="modal" data-bs-target="#open-{{ $meeting->id }}"><i class="ti ti-player-play me-2"></i>Buka sesi</button>@else<div class="mt-3 d-flex justify-content-between align-items-center"><span class="text-secondary small">{{ $session->attendances->count() }} presensi · berakhir {{ $session->expires_at->diffForHumans() }}</span><form method="POST" action="{{ route('lecturer.attendance.close', $session) }}">@csrf<button class="btn btn-sm btn-danger" onclick="return confirm('Tutup sesi presensi ini?')">Tutup</button></form></div>
        <div class="table-responsive mt-3"><table class="table table-sm table-vcenter"><tbody>@foreach($section->studyPlanItems as $planItem)@php($student = $planItem->studyPlan?->enrollment) @php($attendance = $session->attendances->firstWhere('student_enrollment_id', $student?->id))<tr><td><div class="fw-semibold">{{ $student?->studentProfile?->full_name }}</div><div class="small text-secondary">{{ $student?->studentProfile?->student_number }}</div></td><td><form class="d-flex gap-2" method="POST" action="{{ route('lecturer.attendance.record', $session) }}">@csrf<input type="hidden" name="student_enrollment_id" value="{{ $student?->id }}"><select class="form-select form-select-sm" name="status">@foreach(['present'=>'Hadir','late'=>'Terlambat','sick'=>'Sakit','permission'=>'Izin','absent'=>'Tidak hadir'] as $value=>$label)<option value="{{ $value }}" @selected($attendance?->status===$value)>{{ $label }}</option>@endforeach</select>@if($attendance)<input class="form-control form-control-sm" name="reason" placeholder="Alasan koreksi" required>@endif<button class="btn btn-sm btn-primary">Simpan</button></form></td></tr>@endforeach</tbody></table></div>@endif
        </div></div></div>
        <x-tabler.modal id="open-{{ $meeting->id }}" title="Buka sesi presensi"><form method="POST" action="{{ route('lecturer.attendance.open', $meeting) }}">@csrf<div class="mb-3"><label class="form-label required">Metode</label><select class="form-select" name="method" required><option value="manual">Manual</option><option value="pin">PIN</option><option value="qr">QR token</option></select></div><div class="mb-3"><label class="form-label">PIN (khusus metode PIN)</label><input class="form-control" name="pin" inputmode="numeric" pattern="[0-9]{4,8}"></div><div class="mb-3"><label class="form-label required">Durasi (menit)</label><input type="number" class="form-control" name="duration" value="20" min="1" max="240" required></div><button class="btn btn-primary w-100">Buka sesi</button></form></x-tabler.modal>
    @empty<div class="col-12"><x-tabler.empty-state title="Belum ada pertemuan" description="Buat pertemuan kuliah sebelum membuka presensi." icon="ti-calendar-off" /></div>@endforelse
    </div></x-tabler.card></div>
@empty<div class="col-12"><x-tabler.empty-state title="Belum ada kelas" description="Kelas yang Anda ampu akan tampil di sini." icon="ti-school-off" /></div>@endforelse
</div>
@endsection
