@extends('layouts.tabler.lecturer', ['title' => 'Pembelajaran', 'heading' => 'Kelola pembelajaran'])

@section('content')
@if(session('success'))<x-tabler.alert type="success">{{ session('success') }}</x-tabler.alert>@endif
@if($errors->any())<x-tabler.alert type="danger">{{ $errors->first() }}</x-tabler.alert>@endif
<div class="row row-cards">
@forelse($sections as $section)
<div class="col-12"><div class="card">
<div class="card-header"><div><div class="text-secondary small">{{ $section->offering?->course?->code }}</div><h3 class="card-title">{{ $section->offering?->course?->name }} · {{ $section->code }}</h3></div><div class="card-actions btn-list"><button class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#module-{{ $section->id }}"><i class="ti ti-folder-plus me-1"></i>Modul</button><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#assignment-{{ $section->id }}"><i class="ti ti-clipboard-plus me-1"></i>Assignment</button></div></div>
<div class="card-body"><div class="row g-4">
<section class="col-12 col-lg-6"><h4>Modul dan materi</h4>
@forelse($section->courseModules as $module)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between gap-2"><div><strong>{{ $module->position }}. {{ $module->title }}</strong><div><x-tabler.status :value="$module->status" /></div></div><button class="btn btn-sm btn-icon btn-ghost-primary" data-bs-toggle="modal" data-bs-target="#content-{{ $module->id }}" aria-label="Tambah konten"><i class="ti ti-file-plus"></i></button></div><ul class="list-unstyled mt-3 mb-0">@forelse($module->contents as $content)<li class="py-1"><i class="ti {{ $content->type==='url' ? 'ti-link' : 'ti-file-text' }} me-2 text-secondary"></i>{{ $content->title }} @if(!$content->published_at)<span class="badge bg-yellow-lt text-yellow">Draft</span>@endif</li>@empty<li class="text-secondary small">Belum ada konten.</li>@endforelse</ul></div>
<x-tabler.modal id="content-{{ $module->id }}" title="Tambah konten {{ $module->title }}"><form method="POST" action="{{ route('lecturer.learning.contents.store',$module) }}">@csrf<div class="mb-3"><label class="form-label">Jenis</label><select name="type" class="form-select" required><option value="text">Teks</option><option value="url">Tautan</option></select></div><div class="mb-3"><label class="form-label">Judul</label><input name="title" class="form-control" maxlength="160" required></div><div class="mb-3"><label class="form-label">Isi teks</label><textarea name="body" class="form-control" rows="5"></textarea></div><div class="mb-3"><label class="form-label">URL eksternal</label><input type="url" name="external_url" class="form-control"></div><label class="form-check mb-3"><input type="hidden" name="publish_now" value="0"><input type="checkbox" name="publish_now" value="1" class="form-check-input"><span class="form-check-label">Terbitkan sekarang</span></label><button class="btn btn-primary w-100">Simpan konten</button></form></x-tabler.modal>
@empty<x-tabler.empty-state title="Belum ada modul" description="Buat modul agar materi tersusun per topik." icon="ti-folders" />@endforelse
</section>
<section class="col-12 col-lg-6"><h4>Assignment dan submission</h4>
@forelse($section->assignments as $assignment)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><div><strong>{{ $assignment->title }}</strong><div class="small text-secondary">{{ $assignment->due_at?->translatedFormat('d M Y H:i') ?? 'Tanpa tenggat' }}</div></div><x-tabler.status :value="$assignment->status" /></div>
<div class="mt-3">@forelse($assignment->submissions as $submission)<form method="POST" action="{{ route('lecturer.learning.submissions.grade',$submission) }}" class="border-top py-3">@csrf<div class="fw-semibold">{{ $submission->enrollment?->studentProfile?->full_name }}</div><div class="small text-secondary text-truncate mb-2">{{ $submission->answer_text }}</div><div class="row g-2"><div class="col-4"><input type="number" name="score" class="form-control form-control-sm" min="0" max="{{ $assignment->max_score }}" step=".01" value="{{ $submission->score }}" placeholder="Nilai" required></div><div class="col"><input name="feedback" class="form-control form-control-sm" maxlength="5000" value="{{ $submission->feedback }}" placeholder="Umpan balik"></div><div class="col-auto"><button class="btn btn-sm btn-success" onclick="return confirm('Simpan dan kunci nilai submission?')"><i class="ti ti-check"></i></button></div></div></form>@empty<div class="text-secondary small">Belum ada submission.</div>@endforelse</div></div>@empty<x-tabler.empty-state title="Belum ada assignment" description="Buat assignment dengan tenggat dan batas percobaan." icon="ti-clipboard-off" />@endforelse
</section>
</div></div></div></div>
<x-tabler.modal id="module-{{ $section->id }}" title="Buat modul"><form method="POST" action="{{ route('lecturer.learning.modules.store',$section) }}">@csrf<div class="mb-3"><label class="form-label">Judul</label><input name="title" class="form-control" maxlength="160" required></div><div class="mb-3"><label class="form-label">Status</label><select name="status" class="form-select" required><option value="draft">Draft</option><option value="published">Published</option></select></div><button class="btn btn-primary w-100">Buat modul</button></form></x-tabler.modal>
<x-tabler.modal id="assignment-{{ $section->id }}" title="Buat assignment" size="lg"><form method="POST" action="{{ route('lecturer.learning.assignments.store',$section) }}">@csrf<div class="row g-3"><div class="col-12"><label class="form-label">Judul</label><input name="title" class="form-control" maxlength="160" required></div><div class="col-12"><label class="form-label">Instruksi</label><textarea name="instructions" class="form-control" rows="4"></textarea></div><div class="col-md-4"><label class="form-label">Status</label><select name="status" class="form-select"><option value="draft">Draft</option><option value="published">Published</option><option value="open">Open</option></select></div><div class="col-md-4"><label class="form-label">Mulai</label><input type="datetime-local" name="opens_at" class="form-control"></div><div class="col-md-4"><label class="form-label">Tenggat</label><input type="datetime-local" name="due_at" class="form-control"></div><div class="col-md-4"><label class="form-label">Maks. percobaan</label><input type="number" name="max_attempts" class="form-control" min="1" max="10" value="3" required></div><div class="col-md-4"><label class="form-label">Nilai maksimum</label><input type="number" name="max_score" class="form-control" min=".01" max="1000" step=".01" value="100" required></div><div class="col-md-4 d-flex align-items-end"><label class="form-check mb-2"><input type="hidden" name="allow_late" value="0"><input type="checkbox" name="allow_late" value="1" class="form-check-input"><span class="form-check-label">Izinkan terlambat</span></label></div></div><button class="btn btn-primary w-100 mt-3">Buat assignment</button></form></x-tabler.modal>
@empty<div class="col-12"><x-tabler.empty-state title="Belum ada kelas" description="Kelas yang Anda ampu akan tampil di sini." icon="ti-school-off" /></div>@endforelse
</div>
@endsection