@extends('layouts.storefront')

@section('content')
<section class="relative overflow-hidden bg-[#0b1220] text-white">
    <div class="absolute -right-24 top-20 h-96 w-96 rounded-full bg-cyan-400/15 blur-3xl animate-float-slow"></div>
    <div class="absolute left-1/3 top-0 h-72 w-72 rounded-full bg-blue-600/20 blur-3xl"></div>
    <div class="mx-auto grid max-w-7xl gap-14 px-5 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8 lg:py-28">
        <div class="relative z-10 reveal">
            <p class="mb-5 flex items-center gap-2 text-sm font-semibold text-cyan-300"><span class="h-2 w-2 rounded-full bg-cyan-300 animate-pulse"></span> Campus operating system untuk Indonesia</p>
            <h1 class="max-w-3xl font-display text-4xl font-bold leading-[1.05] tracking-tight sm:text-6xl">Satu kendali untuk setiap fase perjalanan mahasiswa.</h1>
            <p class="mt-6 max-w-xl text-lg leading-8 text-slate-300">Dari PMB, KRS, presensi, nilai sampai tagihan dan transkrip—data akademik tidak lagi tercecer di spreadsheet yang tidak saling bicara.</p>
            <div class="mt-9 flex flex-col gap-3 sm:flex-row"><a href="{{ route('login') }}" class="rounded-xl bg-cyan-400 px-6 py-3.5 text-center font-bold text-[#0b1220] shadow-lg shadow-cyan-500/20 transition hover:-translate-y-1">Coba demo</a><a href="{{ route('docs') }}" class="rounded-xl border border-white/20 px-6 py-3.5 text-center font-semibold text-white transition hover:border-cyan-300 hover:text-cyan-200">Lihat dokumentasi</a></div>
            <div class="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-400"><span>✓ UUID-ready</span><span>✓ Role & scope</span><span>✓ Audit trail</span><span>✓ API v1</span></div>
        </div>
        <div class="relative reveal scale-in" style="animation-delay:.12s">
            <div class="rounded-3xl border border-white/10 bg-white/[.06] p-3 shadow-2xl shadow-black/30 backdrop-blur">
                <div class="flex items-center gap-2 border-b border-white/10 px-3 pb-3"><span class="h-2.5 w-2.5 rounded-full bg-rose-400"></span><span class="h-2.5 w-2.5 rounded-full bg-amber-300"></span><span class="h-2.5 w-2.5 rounded-full bg-emerald-400"></span><span class="ml-3 rounded-md bg-white/10 px-3 py-1 text-[10px] text-slate-400">{{ parse_url(config('app.url'), PHP_URL_HOST) }}/admin</span></div>
                <div class="grid gap-3 p-3 sm:grid-cols-2">
                    <div class="rounded-2xl bg-white p-5 text-slate-900 sm:col-span-2"><div class="flex items-start justify-between"><div><p class="text-xs font-semibold text-slate-500">Ringkasan universitas</p><p class="mt-2 text-3xl font-bold">{{ number_format($stats['active_students']) }}</p><p class="text-sm text-slate-500">mahasiswa aktif semester ini</p></div><span class="rounded-lg bg-cyan-50 px-3 py-2 text-xs font-bold text-cyan-700">{{ count($stats['student_trend']) }} angkatan</span></div>@if(count($stats['student_trend']))<div class="mt-5 flex h-16 items-end gap-2" aria-label="Mahasiswa per angkatan">@foreach($stats['student_trend'] as $bar)<span class="flex-1 rounded-t bg-gradient-to-t from-blue-600 to-cyan-300" style="height:{{ $bar['height'] }}%" title="Angkatan {{ $bar['cohort'] }}: {{ $bar['count'] }} mahasiswa"></span>@endforeach</div>@else<x-tabler.empty-state title="Belum ada data angkatan" description="Grafik akan muncul setelah enrollment tersedia." icon="ti-chart-bar" />@endif</div>
                    <div class="rounded-2xl bg-blue-600 p-5"><p class="text-xs text-blue-100">Piutang mahasiswa</p><p class="mt-2 text-2xl font-bold">Rp {{ $stats['outstanding'] }}</p><p class="mt-2 text-xs text-blue-100">saldo invoice dari database</p></div>
                    <div class="rounded-2xl bg-slate-800 p-5"><p class="text-xs text-slate-400">KRS menunggu persetujuan</p><p class="mt-2 text-2xl font-bold">{{ number_format($stats['pending_krs']) }}</p><p class="mt-2 text-xs text-emerald-300">{{ number_format($stats['approved_krs_today']) }} disetujui hari ini</p></div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="border-b border-slate-200 bg-white"><div class="mx-auto grid max-w-7xl grid-cols-2 gap-5 px-5 py-8 sm:grid-cols-4 lg:px-8">@foreach([[$stats['students'],'Profil mahasiswa'],[$stats['programs'],'Program studi'],[$stats['courses'],'Mata kuliah'],[$stats['audit_logs'],'Audit tercatat']] as $stat)<div><p class="font-display text-2xl font-bold text-slate-900">{{ is_numeric($stat[0]) ? number_format($stat[0]) : $stat[0] }}</p><p class="mt-1 text-xs text-slate-500">{{ $stat[1] }}</p></div>@endforeach</div></section>
<section class="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div class="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div class="reveal"><p class="text-sm font-bold text-blue-600">LIFECYCLE DALAM SATU PETA</p><h2 class="mt-3 font-display text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">Data bergerak mengikuti proses kampus.</h2></div><p class="max-w-xl text-slate-600 reveal">Campus ERP menjaga konteks setiap keputusan: siapa yang mengubah, di semester mana, disetujui oleh siapa, dan apa dampaknya ke mahasiswa.</p></div><div class="mt-12 grid gap-4 md:grid-cols-3">@foreach([['01','PMB → Mahasiswa','Pendaftaran, seleksi, registrasi ulang, dan generate NIM.','bg-blue-50 text-blue-700'],['02','Akademik → Transkrip','Kurikulum, offering, KRS, presensi, nilai, KHS, IPK.','bg-cyan-50 text-cyan-700'],['03','Keuangan → Laporan','Invoice, allocation ledger, dashboard eksekutif, dan export.','bg-amber-50 text-amber-700']] as $feature)<article class="card-lift rounded-2xl border border-slate-200 bg-white p-6 shadow-sm reveal"><span class="inline-flex rounded-lg px-3 py-1 text-xs font-bold {{ $feature[3] }}">{{ $feature[0] }}</span><h3 class="mt-5 text-lg font-bold">{{ $feature[1] }}</h3><p class="mt-2 leading-7 text-slate-600">{{ $feature[2] }}</p><a class="mt-6 inline-block text-sm font-bold text-blue-600 hover:underline" href="{{ route('docs') }}">Pelajari alurnya →</a></article>@endforeach</div></section>
<section class="bg-slate-100"><div class="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-2 lg:px-8"><div class="reveal"><p class="text-sm font-bold text-blue-600">DIBUAT UNTUK PERAN YANG BERBEDA</p><h2 class="mt-3 font-display text-3xl font-bold">Satu sumber data, tampilan yang relevan.</h2><p class="mt-5 max-w-lg leading-8 text-slate-600">Rektor melihat pertumbuhan dan risiko. BAAK melihat antrian administrasi. Dosen wali melihat KRS bimbingannya. Mahasiswa melihat langkah berikutnya.</p></div><div class="grid grid-cols-2 gap-3">@foreach([['Rektor','Retention & graduation','bg-[#0b1220] text-white'],['BAAK','KRS & status mahasiswa','bg-white'],['Finance','Piutang & payment ledger','bg-white'],['Mahasiswa','KHS & layanan mandiri','bg-cyan-50']] as $role)<div class="card-lift rounded-2xl border border-slate-200 p-5 {{ $role[2] }}"><div class="mb-8 grid h-10 w-10 place-items-center rounded-xl bg-blue-100 text-blue-700">{{ substr($role[0],0,1) }}</div><p class="font-bold">{{ $role[0] }}</p><p class="mt-1 text-sm opacity-70">{{ $role[1] }}</p></div>@endforeach</div></div></section>
<section class="bg-[#0b1220] text-white"><div class="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-16 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><h2 class="font-display text-3xl font-bold">Mulai dari fondasi akademik yang bisa dipercaya.</h2><p class="mt-3 max-w-xl text-slate-300">Demo data sudah tersedia. Masuk sebagai admin, BAAK, finance, dosen wali, atau mahasiswa.</p></div><a href="{{ route('docs') }}" class="rounded-xl bg-cyan-400 px-6 py-3 font-bold text-[#0b1220]">Buka akun demo</a></div></section>
@endsection
