@extends('layouts.storefront', ['title' => 'Dokumentasi Campus ERP — SIAKAD Universitas'])
@section('content')
<section class="bg-[#0b1220] py-16 text-white"><div class="mx-auto max-w-7xl px-5 lg:px-8"><p class="text-sm font-bold text-cyan-300">DOKUMENTASI PRODUK</p><h1 class="mt-3 max-w-3xl font-display text-4xl font-bold leading-tight sm:text-5xl">Cara kerja Campus ERP dari setup sampai transkrip.</h1><p class="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Panduan singkat untuk tim pimpinan, BAAK, finance, dosen, dan mahasiswa. Semua contoh mengikuti data demo Universitas Cakrawala Nusantara.</p></div></section>
<div class="sticky top-[73px] z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div class="mx-auto flex max-w-7xl gap-5 overflow-x-auto px-5 py-3 text-sm font-semibold lg:px-8"><a href="#akun">Akun demo</a><a href="#menu">Menu</a><a href="#tutorial">Tutorial</a><a href="#fitur">Fitur</a></div></div>
<section id="akun" class="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div class="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p class="text-sm font-bold text-blue-600">01 · AKUN DEMO</p><h2 class="mt-3 font-display text-3xl font-bold">Masuk sesuai tanggung jawab Anda.</h2><p class="mt-4 leading-7 text-slate-600">Setiap peran mendapatkan konteks yang berbeda. Coba akun berikut di <a class="font-semibold text-blue-600" href="{{ route('login') }}">halaman masuk</a>.</p></div><div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table class="w-full min-w-[640px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Peran</th><th class="px-5 py-3">Email</th><th class="px-5 py-3">Password</th><th class="px-5 py-3">Cakupan</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($accounts as $account)<tr><td class="px-5 py-4 font-semibold">{{ $account['role'] }}</td><td class="px-5 py-4 font-mono text-xs">{{ $account['email'] }}</td><td class="px-5 py-4 font-mono text-xs">{{ $account['password'] }}</td><td class="px-5 py-4 text-slate-500">{{ $account['scope'] }}</td></tr>@endforeach</tbody></table></div></div></section>
<section id="menu" class="bg-slate-100"><div class="mx-auto max-w-7xl px-5 py-14 lg:px-8"><p class="text-sm font-bold text-blue-600">02 · STRUKTUR MENU</p><div class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach([['Dashboard','Ringkasan eksekutif, filter scope, alert approval'],['Master Data','Organisasi, prodi, kurikulum, mata kuliah'],['Akademik','Semester, offering, kelas, jadwal, KRS'],['Mahasiswa','Profil, enrollment, status, histori'],['Dosen','Employee, NIDN, beban mengajar, wali'],['Keuangan','Fee, invoice, payment, allocation ledger'],['Laporan','Akademik, finance, operasional, export'],['Sistem','Users, role, audit log, settings, backup']] as $item)<div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="font-bold">{{ $item[0] }}</p><p class="mt-2 text-sm leading-6 text-slate-500">{{ $item[1] }}</p></div>@endforeach</div></div></section>
<section id="tutorial" class="mx-auto max-w-7xl px-5 py-14 lg:px-8"><p class="text-sm font-bold text-blue-600">03 · TUTORIAL BERURUT</p><h2 class="mt-3 font-display text-3xl font-bold">Enam fase untuk menjalankan semester.</h2><div class="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">@foreach($tutorial as $phase => $steps)<article class="rounded-2xl border border-slate-200 bg-white p-6"><h3 class="font-display text-lg font-bold">{{ $phase }}</h3><ol class="mt-5 space-y-3">@foreach($steps as $step)<li class="flex gap-3 text-sm leading-6 text-slate-600"><span class="font-mono text-xs font-bold text-blue-600">{{ $loop->iteration }}</span><span>{{ $step }}</span></li>@endforeach</ol></article>@endforeach</div></section>
<section id="fitur" class="bg-[#0b1220] text-white"><div class="mx-auto max-w-7xl px-5 py-14 lg:px-8"><p class="text-sm font-bold text-cyan-300">04 · FITUR INTI</p><div class="mt-8 grid gap-5 lg:grid-cols-3">@foreach([['Identity & scope','Satu identitas untuk employee, dosen, mahasiswa, dan alumni. Role dapat dibatasi universitas, kampus, fakultas, atau prodi.'],['KRS dengan aturan','Validasi kapasitas, prasyarat, bentrok jadwal, financial hold, batas SKS, lalu approval dosen wali.'],['Grade lifecycle','Nilai punya komponen, skala, status draft hingga locked. Perubahan setelah locked membutuhkan approval.'],['Presensi anti-manipulasi','Sesi attendance menyimpan metode, expiry, perangkat, IP, dan histori audit.'],['Ledger keuangan','Payment tidak mengubah invoice secara magis; setiap pembayaran dialokasikan melalui payment_allocations.'],['API & automasi','API v1, event internal, queue, scheduler, backup, dan IndexNow disiapkan untuk pertumbuhan.']] as $feature)<article class="rounded-2xl border border-white/10 bg-white/5 p-6"><h3 class="font-display text-xl font-bold">{{ $feature[0] }}</h3><p class="mt-3 leading-7 text-slate-300">{{ $feature[1] }}</p></article>@endforeach</div></div></section>
<section class="mx-auto max-w-7xl px-5 py-14 text-center lg:px-8"><h2 class="font-display text-3xl font-bold">Siap menjelajah ruang kerja kampus?</h2><p class="mx-auto mt-3 max-w-xl text-slate-600">Gunakan akun demo untuk melihat dashboard dan portal yang sudah terisi data realistis.</p><a href="{{ route('login') }}" class="mt-6 inline-flex rounded-xl bg-[#0b1220] px-6 py-3.5 font-bold text-white">Masuk sekarang</a></section>
@endsection
