@extends('layouts.tabler.admin', ['title' => 'Approval Nilai'])

@section('content')
<div class="page-header d-print-none"><div class="container-xl"><x-tabler.page-header title="Approval dan publikasi nilai" description="Tinjau urutan status nilai sebelum tersedia pada KHS dan transkrip." /></div></div>
<div class="page-body"><div class="container-xl">
@if(session('success'))<x-tabler.alert type="success">{{ session('success') }}</x-tabler.alert>@endif
@if($errors->any())<x-tabler.alert type="danger">{{ $errors->first() }}</x-tabler.alert>@endif
<x-tabler.card><form method="GET" class="row g-2 mb-3"><div class="col-12 col-sm-4"><select class="form-select" name="status"><option value="">Semua status</option>@foreach(['draft','submitted','approved','published','locked'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-outline-primary"><i class="ti ti-filter me-2"></i>Filter</button></div></form>
@if($grades->isEmpty())<x-tabler.empty-state title="Tidak ada nilai" description="Nilai yang disubmit dosen akan tampil untuk ditinjau." icon="ti-file-check" />@else<div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Mahasiswa</th><th>Mata kuliah</th><th>Nilai</th><th>Status</th><th class="w-1"></th></tr></thead><tbody>@foreach($grades as $grade)<tr><td><div class="fw-semibold">{{ $grade->studyPlanItem?->studyPlan?->enrollment?->studentProfile?->full_name }}</div><div class="text-secondary small">{{ $grade->studyPlanItem?->studyPlan?->enrollment?->studentProfile?->student_number }}</div></td><td>{{ $grade->studyPlanItem?->classSection?->offering?->course?->name }}</td><td><span class="fw-bold">{{ $grade->final_score ?? '—' }}</span> <span class="badge bg-green-lt text-green">{{ $grade->gradeScale?->grade ?? '—' }}</span></td><td><x-tabler.status :value="$grade->status" /></td><td>@php($next=['submitted'=>'approve','approved'=>'publish','published'=>'lock'][$grade->status]??null)@if($next)<form method="POST" action="{{ route('admin.grades.transition',$grade) }}">@csrf<input type="hidden" name="action" value="{{ $next }}"><button class="btn btn-sm btn-primary" onclick="return confirm('Lanjutkan status nilai ini?')">{{ ['approve'=>'Setujui','publish'=>'Publikasikan','lock'=>'Kunci'][$next] }}</button></form>@endif</td></tr>@endforeach</tbody></table></div>{{ $grades->links() }}@endif
</x-tabler.card></div></div>
@endsection
