[program:kampus-worker]
command=php /var/www/kampus/artisan queue:work --sleep=3 --tries=3 --timeout=120
directory=/var/www/kampus
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/kampus-worker.log
