<!doctype html>
<html lang="{{ $locale }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $locale === 'en' ? 'Academic Transcript' : 'Transkrip Akademik' }} — {{ $enrollment->studentProfile?->student_number }}</title>@vite(['resources/css/app.css'])<style>@page{size:A4;margin:16mm}body{font-size:12px}.document-header{border-bottom:3px solid var(--tblr-primary);padding-bottom:1rem;margin-bottom:1.5rem}.document-meta{display:grid;grid-template-columns:9rem 1fr;gap:.25rem 1rem}.table th{font-size:10px}@media print{.no-print{display:none!important}.card{box-shadow:none!important;border:0!important}}</style></head>
<body><main class="container-xl py-4"><div class="d-flex justify-content-end mb-3 no-print"><button class="btn btn-primary" onclick="window.print()"><i class="ti ti-printer me-2"></i>{{ $locale === 'en' ? 'Print / Save PDF' : 'Cetak / Simpan PDF' }}</button></div>
<header class="document-header d-flex align-items-center gap-3">@if($brand['logo'])<img src="{{ Storage::url($brand['logo']) }}" alt="{{ $brand['name'] }}" style="width:64px;height:64px;object-fit:contain">@else<span class="avatar avatar-xl bg-primary text-white">{{ str($brand['shortName'])->substr(0,1) }}</span>@endif<div><h1 class="h2 mb-1">{{ $brand['name'] }}</h1><div class="text-secondary">{{ $locale === 'en' ? 'Temporary Academic Transcript' : 'Transkrip Akademik Sementara' }}</div></div></header>
<section class="document-meta mb-4"><strong>{{ $locale === 'en' ? 'Student name' : 'Nama mahasiswa' }}</strong><span>{{ $enrollment->studentProfile?->full_name }}</span><strong>{{ $locale === 'en' ? 'Student number' : 'NIM' }}</strong><span>{{ $enrollment->studentProfile?->student_number }}</span><strong>{{ $locale === 'en' ? 'Study program' : 'Program studi' }}</strong><span>{{ $enrollment->studyProgram?->name }}</span><strong>{{ $locale === 'en' ? 'Academic status' : 'Status akademik' }}</strong><span>{{ ucfirst($enrollment->status) }}</span></section>
<table class="table table-bordered table-vcenter"><thead><tr><th>No.</th><th>{{ $locale === 'en' ? 'Code' : 'Kode' }}</th><th>{{ $locale === 'en' ? 'Course' : 'Mata kuliah' }}</th><th class="text-center">SKS</th><th class="text-center">{{ $locale === 'en' ? 'Grade' : 'Nilai' }}</th><th class="text-center">{{ $locale === 'en' ? 'Point' : 'Bobot' }}</th></tr></thead><tbody>@foreach($record['transcript_items'] as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->classSection?->offering?->course?->code }}</td><td>{{ $item->classSection?->offering?->course?->name }}</td><td class="text-center">{{ $item->credits }}</td><td class="text-center fw-bold">{{ $item->grade?->gradeScale?->grade }}</td><td class="text-center">{{ number_format((float)$item->grade?->gradeScale?->grade_point,2) }}</td></tr>@endforeach</tbody></table>
<div class="row mt-4"><div class="col-6"><div class="text-secondary">{{ $locale === 'en' ? 'Repeat-course policy' : 'Kebijakan mata kuliah ulang' }}</div><strong>{{ str_replace('_',' ',$record['repeat_policy']) }}</strong></div><div class="col-6 text-end"><div>{{ $locale === 'en' ? 'Earned credits' : 'SKS lulus' }}: <strong>{{ $record['earned_credits'] }}</strong></div><div>{{ $locale === 'en' ? 'Cumulative GPA' : 'IPK' }}: <strong>{{ number_format($record['gpa'],2) }}</strong></div></div></div>
<footer class="text-secondary small mt-5 pt-3 border-top">{{ $locale === 'en' ? 'Generated' : 'Dibuat' }} {{ now()->translatedFormat('d F Y H:i') }} · {{ $locale === 'en' ? 'This temporary document is not a final diploma attachment.' : 'Dokumen sementara ini bukan lampiran ijazah final.' }}</footer></main></body></html>
