@extends('portal.layout', ['heading' => 'Ringkasan akademik'])
@section('content')
@php
    $outstandingMinor = $enrollment->invoices->reduce(fn (int $total, $invoice) => $total + App\Support\Money::toMinorUnits($invoice->outstanding_amount), 0);
    $outstandingLabel = 'Rp '.number_format(intdiv($outstandingMinor, 100), 0, ',', '.');
@endphp
<div class="card bg-dark text-white overflow-hidden mb-4"><div class="card-body p-4 p-md-5"><div class="row align-items-end g-4"><div class="col"><div class="text-azure mb-2">Selamat datang kembali, {{ Str::before($enrollment->studentProfile->full_name, ' ') }}.</div><h2 class="h1 text-white mb-2">Semester akademik berjalan</h2><div class="text-white-50">{{ $enrollment->studyProgram->name }} · Angkatan {{ $enrollment->cohort }}</div></div><div class="col-auto"><div class="bg-white bg-opacity-10 rounded p-3"><div class="small text-white-50">Status akademik</div><div class="fw-bold text-success mt-1">{{ str($enrollment->status)->title() }}</div></div></div></div></div></div>
<div class="row row-deck row-cards mb-4"><div class="col-12 col-sm-6 col-xl-4"><x-tabler.stat-card label="IPK" :value="number_format($gpa, 2)" icon="ti-chart-line" color="azure" description="Berdasarkan nilai yang telah terbit" /></div><div class="col-12 col-sm-6 col-xl-4"><x-tabler.stat-card label="SKS semester" :value="$plan?->total_credits ?? 0" icon="ti-books" color="teal" description="KRS semester berjalan" /></div><div class="col-12 col-sm-6 col-xl-4"><x-tabler.stat-card label="Sisa tagihan" :value="$outstandingLabel" icon="ti-file-invoice" color="orange" description="Saldo seluruh invoice aktif" /></div></div>
<div class="row row-cards"><div class="col-12 col-xl-8"><x-tabler.card title="Kelas semester ini"><div class="list-group list-group-flush">@forelse($plan?->items ?? [] as $item)<div class="list-group-item px-0"><div class="row align-items-center"><div class="col"><div class="fw-semibold">{{ $item->classSection->offering->course->name }}</div><div class="text-secondary small mt-1">{{ $item->classSection->offering->course->code }} · Kelas {{ $item->classSection->code }} · {{ $item->credits }} SKS</div></div><div class="col-auto"><x-tabler.status :value="$item->grade?->status ?? $item->status" /></div></div></div>@empty<x-tabler.empty-state title="Belum ada KRS" description="Mata kuliah akan muncul setelah KRS disimpan." icon="ti-books-off" />@endforelse</div><x-slot:footer><a href="{{ route('portal.krs') }}" class="btn btn-primary"><i class="ti ti-checklist me-2"></i>Lihat KRS</a></x-slot:footer></x-tabler.card></div><div class="col-12 col-xl-4"><x-tabler.card title="Dosen wali"><div class="d-flex gap-3 align-items-center"><span class="avatar avatar-lg bg-blue-lt text-blue"><i class="ti ti-user-star fs-2"></i></span><div><div class="fw-semibold">{{ $enrollment->advisor?->employee?->full_name ?? 'Belum ditentukan' }}</div><div class="text-secondary small">{{ $enrollment->advisor?->academic_rank ?? 'Dosen wali' }}</div></div></div><p class="text-secondary mt-4 mb-0">Gunakan data KRS, KHS, dan IPK sebagai dasar konsultasi rencana studi.</p></x-tabler.card></div></div>
@endsection